// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && integration

package vswitch

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type statsProbeSlotStats struct {
	_    structs.HostLayout
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	Pad              uint32
	Generation       uint64
	MgmtRxPackets    uint64
	MgmtRxBytes      uint64
	MgmtTxPackets    uint64
	MgmtTxBytes      uint64
	TransitRxPackets uint64
	TransitRxBytes   uint64
	TransitTxPackets uint64
	TransitTxBytes   uint64
}

// loadStatsProbe returns the embedded CollectionSpec for statsProbe.
func loadStatsProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_StatsProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load statsProbe: %w", err)
	}

	return spec, err
}

// loadStatsProbeObjects loads statsProbe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*statsProbeObjects
//	*statsProbePrograms
//	*statsProbeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadStatsProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadStatsProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// statsProbeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type statsProbeSpecs struct {
	statsProbeProgramSpecs
	statsProbeMapSpecs
	statsProbeVariableSpecs
}

// statsProbeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type statsProbeProgramSpecs struct {
	LateStatsWrite *ebpf.ProgramSpec `ebpf:"late_stats_write"`
}

// statsProbeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type statsProbeMapSpecs struct {
	Stats *ebpf.MapSpec `ebpf:"stats"`
}

// statsProbeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type statsProbeVariableSpecs struct {
}

// statsProbeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadStatsProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type statsProbeObjects struct {
	statsProbePrograms
	statsProbeMaps
	statsProbeVariables
}

func (o *statsProbeObjects) Close() error {
	return _StatsProbeClose(
		&o.statsProbePrograms,
		&o.statsProbeMaps,
	)
}

// statsProbeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadStatsProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type statsProbeMaps struct {
	Stats *ebpf.Map `ebpf:"stats"`
}

func (m *statsProbeMaps) Close() error {
	return _StatsProbeClose(
		m.Stats,
	)
}

// statsProbeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadStatsProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type statsProbeVariables struct {
}

// statsProbePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadStatsProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type statsProbePrograms struct {
	LateStatsWrite *ebpf.Program `ebpf:"late_stats_write"`
}

func (p *statsProbePrograms) Close() error {
	return _StatsProbeClose(
		p.LateStatsWrite,
	)
}

func _StatsProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed statsprobe_x86_bpfel_test.o
var _StatsProbeBytes []byte
