// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type vswitchExportedU32 uint32

const (
	vswitchExportedU32MAX_PORTS               vswitchExportedU32 = 4096
	vswitchExportedU32MAX_MGMT_CIDR_PER_SLOT  vswitchExportedU32 = 3
	vswitchExportedU32INNER_IP_FREE           vswitchExportedU32 = 0
	vswitchExportedU32INNER_IP_RESERVED       vswitchExportedU32 = 4294967295
	vswitchExportedU32PORT_KIND_VETH          vswitchExportedU32 = 0
	vswitchExportedU32PORT_KIND_TAP           vswitchExportedU32 = 1
	vswitchExportedU32MAX_GENEVE_OPTS_LEN     vswitchExportedU32 = 64
	vswitchExportedU32GENEVE_PORT             vswitchExportedU32 = 6081
	vswitchExportedU32GENEVE_LOCATOR_PORT     vswitchExportedU32 = 0
	vswitchExportedU32GENEVE_LOCATOR_VNI      vswitchExportedU32 = 1
	vswitchExportedU32GENEVE_LOCATOR_TLV      vswitchExportedU32 = 2
	vswitchExportedU32GENEVE_VNI_LOCATOR_BITS vswitchExportedU32 = 12
	vswitchExportedU32GENEVE_VNI_VALUE_MASK   vswitchExportedU32 = 4095
)

type vswitchGeneveOptsValue struct {
	_        structs.HostLayout
	Len      uint8
	Critical uint8
	Reserved uint16
	Data     [64]uint8
}

type vswitchMgmtCidr struct {
	_       structs.HostLayout
	Ip      uint32
	Mask    uint32
	Ifindex uint32
	MgmtMac [6]uint8
	Pad     [2]uint8
}

type vswitchSlotItem struct {
	_                structs.HostLayout
	Ifindex          uint32
	InnerIp          uint32
	TransitIfindex   uint32
	TransitIp        uint32
	TransitGatewayIp uint32
	TransitGeneveVni uint32
	TransitMac       [6]uint8
	Mode             uint8
	GeneveOptsLen    uint8
	MgmtCidrCount    uint32
	MgmtCidrs0       vswitchMgmtCidr
	PadCl0           [8]uint8
	MgmtCidrsExt     [2]vswitchMgmtCidr
	StatsReady       uint32
}

type vswitchSlotStats struct {
	_    structs.HostLayout
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	Pad              uint32
	Generation       uint64
	MgmtRxPackets    uint64
	MgmtRxBytes      uint64
	MgmtTxPackets    uint64
	MgmtTxBytes      uint64
	TransitRxPackets uint64
	TransitRxBytes   uint64
	TransitTxPackets uint64
	TransitTxBytes   uint64
}

type vswitchSvcKey struct {
	_     structs.HostLayout
	Ip    uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

type vswitchSvcVal struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	Pad  uint16
}

type vswitchSwitchConfig struct {
	_              structs.HostLayout
	SwitchMac      [6]uint8
	Pad            uint16
	N_ports        uint32
	FloatingIpBase uint32
	GenevePortBase uint32
	GeneveEncapEth uint8
	Pad3           [3]uint8
	TransitNexthop uint32
	PortMac        [6]uint8
	Pad4           [2]uint8
	GeneveLocator  uint8
	GeneveTlvType  uint8
	GeneveTlvClass uint16
}

// loadVswitch returns the embedded CollectionSpec for vswitch.
func loadVswitch() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_VswitchBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load vswitch: %w", err)
	}

	return spec, err
}

// loadVswitchObjects loads vswitch and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*vswitchObjects
//	*vswitchPrograms
//	*vswitchMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadVswitchObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadVswitch()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// vswitchSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type vswitchSpecs struct {
	vswitchProgramSpecs
	vswitchMapSpecs
	vswitchVariableSpecs
}

// vswitchProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type vswitchProgramSpecs struct {
	TcIngressMx      *ebpf.ProgramSpec `ebpf:"tc_ingress_mx"`
	TcIngressNx      *ebpf.ProgramSpec `ebpf:"tc_ingress_nx"`
	TcIngressTransit *ebpf.ProgramSpec `ebpf:"tc_ingress_transit"`
}

// vswitchMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type vswitchMapSpecs struct {
	Config        *ebpf.MapSpec `ebpf:"config"`
	GeneveOpts    *ebpf.MapSpec `ebpf:"geneve_opts"`
	IfindexToSlot *ebpf.MapSpec `ebpf:"ifindex_to_slot"`
	Metadata      *ebpf.MapSpec `ebpf:"metadata"`
	MgmtSvcFwd    *ebpf.MapSpec `ebpf:"mgmt_svc_fwd"`
	MgmtSvcRev    *ebpf.MapSpec `ebpf:"mgmt_svc_rev"`
	Slots         *ebpf.MapSpec `ebpf:"slots"`
	Stats         *ebpf.MapSpec `ebpf:"stats"`
}

// vswitchVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type vswitchVariableSpecs struct {
}

// vswitchObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadVswitchObjects or ebpf.CollectionSpec.LoadAndAssign.
type vswitchObjects struct {
	vswitchPrograms
	vswitchMaps
	vswitchVariables
}

func (o *vswitchObjects) Close() error {
	return _VswitchClose(
		&o.vswitchPrograms,
		&o.vswitchMaps,
	)
}

// vswitchMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadVswitchObjects or ebpf.CollectionSpec.LoadAndAssign.
type vswitchMaps struct {
	Config        *ebpf.Map `ebpf:"config"`
	GeneveOpts    *ebpf.Map `ebpf:"geneve_opts"`
	IfindexToSlot *ebpf.Map `ebpf:"ifindex_to_slot"`
	Metadata      *ebpf.Map `ebpf:"metadata"`
	MgmtSvcFwd    *ebpf.Map `ebpf:"mgmt_svc_fwd"`
	MgmtSvcRev    *ebpf.Map `ebpf:"mgmt_svc_rev"`
	Slots         *ebpf.Map `ebpf:"slots"`
	Stats         *ebpf.Map `ebpf:"stats"`
}

func (m *vswitchMaps) Close() error {
	return _VswitchClose(
		m.Config,
		m.GeneveOpts,
		m.IfindexToSlot,
		m.Metadata,
		m.MgmtSvcFwd,
		m.MgmtSvcRev,
		m.Slots,
		m.Stats,
	)
}

// vswitchVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadVswitchObjects or ebpf.CollectionSpec.LoadAndAssign.
type vswitchVariables struct {
}

// vswitchPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadVswitchObjects or ebpf.CollectionSpec.LoadAndAssign.
type vswitchPrograms struct {
	TcIngressMx      *ebpf.Program `ebpf:"tc_ingress_mx"`
	TcIngressNx      *ebpf.Program `ebpf:"tc_ingress_nx"`
	TcIngressTransit *ebpf.Program `ebpf:"tc_ingress_transit"`
}

func (p *vswitchPrograms) Close() error {
	return _VswitchClose(
		p.TcIngressMx,
		p.TcIngressNx,
		p.TcIngressTransit,
	)
}

func _VswitchClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed vswitch_arm64_bpfel.o
var _VswitchBytes []byte
